package com.example;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CITY".
 */
@Entity
public class City {
    private String cityZh;

    @Override
    public String toString() {
        return "City{" +
                "cityZh='" + cityZh + '\'' +
                ", provinceZh='" + provinceZh + '\'' +
                ", leaderZh='" + leaderZh + '\'' +
                '}';
    }

    private String provinceZh;
    private String leaderZh;

    @Generated
    public City() {
    }

    @Generated
    public City(String cityZh, String provinceZh, String leaderZh) {
        this.cityZh = cityZh;
        this.provinceZh = provinceZh;
        this.leaderZh = leaderZh;
    }

    public String getCityZh() {
        return cityZh;
    }

    public void setCityZh(String cityZh) {
        this.cityZh = cityZh;
    }

    public String getProvinceZh() {
        return provinceZh;
    }

    public void setProvinceZh(String provinceZh) {
        this.provinceZh = provinceZh;
    }

    public String getLeaderZh() {
        return leaderZh;
    }

    public void setLeaderZh(String leaderZh) {
        this.leaderZh = leaderZh;
    }

}
